[package]
name = "yet-lamport-clock"
version = "0.1.0"
edition = "2024"

[lib]
name = "clock"
path = "src/lib.rs"

[dependencies]
rand = "0.9.2"

# Reference: <https://doc.rust-lang.org/stable/clippy/>.
[lints.clippy]
all = "warn" # This lint (alone) includes `correctness`, `suspicious`, `style`, `complexity`, and `perf`.
pedantic = "warn"
nursery = "warn"
